name: First
on:
  pull_request:
    branches:
      - master
jobs:
#veracode
  veracode_sast_upload_v210929:
    name: Veracode Scan
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_STAGE: stg
    steps:    
      - name: test
        run: echo "First job"